-- FamilyBudget: every migration, in order, as one file.
-- Generated by scripts/build-bootstrap-sql.sh. Do not edit by hand.
--
-- For setting up a fresh database without Node, for example by pasting
-- into the psql console in the Render dashboard. It runs in a single
-- transaction, so a failure anywhere leaves the database untouched, and
-- it records each file in schema_migrations, so a later 'npm run migrate'
-- sees the work as already done and changes nothing.

begin;

create table if not exists schema_migrations (
  filename    text primary key,
  applied_at  timestamptz not null default now()
);

-- ============================================================
-- 001_init.sql
-- ============================================================
-- Stage 1 schema: accounts, transactions, balances, sync runs, users.
-- Targets PostgreSQL 18 on Render. gen_random_uuid() is built in since 13, so
-- no extension is needed.

create table users (
  id             uuid primary key default gen_random_uuid(),
  email          text not null unique,
  password_hash  text not null,
  created_at     timestamptz not null default now()
);

-- Accounts come from Redbark, or are created by hand later (an ING personal
-- loan that open banking does not expose, for example). Role and is_liquid are
-- set through the UI and never hardcoded, so account numbers stay out of the
-- source.
create table accounts (
  id                     uuid primary key default gen_random_uuid(),
  source                 text not null default 'redbark' check (source in ('redbark', 'manual')),
  redbark_connection_id  text,
  redbark_account_id     text unique,
  bank                   text not null,
  name                   text not null,
  masked_number          text,
  -- What the bank calls it, for example transaction or loan.
  type                   text,
  -- What it means to us. Null until someone sets it in the UI.
  role                   text check (role in (
                           'joint_everyday', 'personal_everyday',
                           'personal_savings', 'mortgage', 'other'
                         )),
  is_liquid              boolean not null default false,
  currency               text not null default 'aud',
  -- Redbark's view of the account, for example available.
  status                 text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  -- A redbark account must carry its redbark id, a manual one must not.
  constraint accounts_source_ids check (
    (source = 'redbark' and redbark_account_id is not null)
    or (source = 'manual' and redbark_account_id is null)
  )
);

create index accounts_role_idx on accounts (role);

create table transactions (
  id                   uuid primary key default gen_random_uuid(),
  account_id           uuid not null references accounts (id) on delete cascade,
  redbark_txn_id       text not null,
  status               text not null check (status in ('pending', 'posted')),
  txn_date             date not null,
  posted_date          date,
  description          text not null default '',
  -- Negative is money out. On a loan account the sign inverts in meaning: a
  -- repayment arrives positive because it reduces the debt, and interest
  -- charged is negative. That is what makes a mortgage repayment pair up as
  -- equal and opposite against the ING side.
  amount               numeric(12,2) not null,
  -- Extra provider fields. They cost nothing to keep and they carry the hints
  -- that transfer matching relies on.
  direction            text,
  reference            text,
  extended_description text,
  merchant_name        text,
  provider_category    text,
  raw                  jsonb not null,
  is_transfer          boolean not null default false,
  transfer_pair_id     uuid references transactions (id) on delete set null,
  transfer_confidence  text check (transfer_confidence in ('auto', 'confirmed', 'rejected')),
  -- Stage 2 will add the categories table. The column exists now so the join
  -- can be added without touching this table again.
  category_id          uuid,
  first_seen_at        timestamptz not null default now(),
  last_seen_at         timestamptz not null default now(),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  constraint transactions_account_redbark_id_key unique (account_id, redbark_txn_id)
);

create index transactions_account_date_idx on transactions (account_id, txn_date desc);
create index transactions_date_idx on transactions (txn_date desc);
create index transactions_status_idx on transactions (status);
-- Transfer detection scans unpaired rows by amount and date.
create index transactions_unpaired_idx on transactions (amount, txn_date)
  where transfer_pair_id is null;

-- One balance snapshot per account per day, upserted through the day.
create table balances (
  id                uuid primary key default gen_random_uuid(),
  account_id        uuid not null references accounts (id) on delete cascade,
  balance_date      date not null,
  balance           numeric(12,2),
  available_balance numeric(12,2),
  -- When the bank actually observed it, and whether Redbark considers that
  -- reading fresh, stale or unavailable.
  observed_at       timestamptz,
  freshness         text,
  captured_at       timestamptz not null default now(),
  constraint balances_account_date_key unique (account_id, balance_date)
);

-- Rejecting a transfer is about the pair, not the rows. A transaction wrongly
-- offered against one counterpart must still be pairable with the right one,
-- so the rejection is stored per pair. Rows are held in a stable order so a
-- pair is recorded once whichever way round it is offered.
create table transfer_rejections (
  txn_low_id   uuid not null references transactions (id) on delete cascade,
  txn_high_id  uuid not null references transactions (id) on delete cascade,
  rejected_at  timestamptz not null default now(),
  primary key (txn_low_id, txn_high_id),
  constraint transfer_rejections_ordered check (txn_low_id < txn_high_id)
);

create table sync_runs (
  id                 uuid primary key default gen_random_uuid(),
  started_at         timestamptz not null default now(),
  finished_at        timestamptz,
  status             text not null default 'running' check (status in ('running', 'success', 'partial', 'failed')),
  accounts_synced    integer not null default 0,
  txns_inserted      integer not null default 0,
  txns_updated       integer not null default 0,
  pending_resolved   integer not null default 0,
  pending_expired    integer not null default 0,
  transfers_detected integer not null default 0,
  error_message      text
);

create index sync_runs_started_idx on sync_runs (started_at desc);

insert into schema_migrations (filename) values ('001_init.sql') on conflict do nothing;

-- ============================================================
-- 002_session_store.sql
-- ============================================================
-- Session table for connect-pg-simple. This is the library's own schema, kept
-- here as a migration so the database is built by one mechanism rather than
-- letting the library create tables at boot.
create table "session" (
  "sid"    varchar not null collate "default",
  "sess"   json not null,
  "expire" timestamp(6) not null
);

alter table "session"
  add constraint "session_pkey" primary key ("sid") not deferrable initially immediate;

create index "IDX_session_expire" on "session" ("expire");

insert into schema_migrations (filename) values ('002_session_store.sql') on conflict do nothing;

-- ============================================================
-- 003_categories_and_rules.sql
-- ============================================================
-- Stage 2: categories and rules.

-- A group is a row with parent_id null. A category sits inside a group.
create table categories (
  id          uuid primary key default gen_random_uuid(),
  parent_id   uuid references categories (id) on delete cascade,
  name        text not null,
  -- How the category behaves in later stages. Transfers and ignored rows are
  -- excluded from spending, income feeds the buckets.
  kind        text not null default 'expense'
              check (kind in ('income', 'expense', 'transfer', 'ignore')),
  colour      text,
  sort_order  integer not null default 0,
  archived    boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  -- Two groups cannot share a name, and neither can two categories in the same
  -- group. NULLS NOT DISTINCT makes the group level work, which plain unique
  -- would not because every null differs.
  constraint categories_name_unique unique nulls not distinct (parent_id, name)
);

create index categories_parent_idx on categories (parent_id, sort_order);

-- category_id was added in Stage 1 with no table to point at. Wire it up now.
alter table transactions
  add constraint transactions_category_fk
  foreign key (category_id) references categories (id) on delete set null;

alter table transactions
  -- Where the category came from, so recategorising never overwrites a choice
  -- a person made by hand.
  add column category_source text
    check (category_source in ('manual', 'rule', 'provider')),
  add column categorised_by_rule_id uuid,
  -- Rules can rename a transaction for display, and annotate it. The original
  -- description is never touched.
  add column display_description text,
  add column note text;

create index transactions_category_idx on transactions (category_id);

-- Redbark supplies a provider category on most rows. Mapping it gives every
-- transaction a reasonable starting category without writing a rule for each.
create table provider_category_map (
  provider_category text primary key,
  category_id       uuid not null references categories (id) on delete cascade,
  created_at        timestamptz not null default now()
);

-- Ordered rules, evaluated top to bottom, first match wins.
create table rules (
  id          uuid primary key default gen_random_uuid(),
  position    integer not null,
  name        text not null,
  enabled     boolean not null default true,

  -- Conditions. Every condition that is set must match. All null means the rule
  -- matches everything, which is useful only as a catch all at the bottom.
  match_field text not null default 'any'
              check (match_field in ('any', 'description', 'merchant_name', 'reference', 'extended_description')),
  match_type  text not null default 'contains'
              check (match_type in ('contains', 'equals', 'starts_with', 'regex')),
  match_value text,
  account_id  uuid references accounts (id) on delete cascade,
  direction   text check (direction in ('debit', 'credit')),
  min_amount  numeric(12,2),
  max_amount  numeric(12,2),

  -- Actions.
  category_id uuid references categories (id) on delete set null,
  rename_to   text,
  set_note    text,
  mark_ignore boolean not null default false,

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index rules_position_idx on rules (position);

alter table transactions
  add constraint transactions_rule_fk
  foreign key (categorised_by_rule_id) references rules (id) on delete set null;

-- Counts for the sync run, so categorising is visible like everything else.
alter table sync_runs
  add column txns_categorised integer not null default 0;

insert into schema_migrations (filename) values ('003_categories_and_rules.sql') on conflict do nothing;

-- ============================================================
-- 004_seed_taxonomy.sql
-- ============================================================
-- A starting taxonomy for an Australian household, and a mapping from every
-- top level Redbark provider category onto it, so transactions land somewhere
-- sensible before a single rule is written. All of it is editable in the UI.

insert into categories (parent_id, name, kind, sort_order) values
  (null, 'Income',     'income',   10),
  (null, 'Home',       'expense',  20),
  (null, 'Everyday',   'expense',  30),
  (null, 'Transport',  'expense',  40),
  (null, 'Health',     'expense',  50),
  (null, 'Lifestyle',  'expense',  60),
  (null, 'Money',      'expense',  70),
  (null, 'Transfers',  'transfer', 80);

insert into categories (parent_id, name, kind, sort_order)
select g.id, c.name, c.kind, c.sort_order
from (values
  ('Income',    'Pay',                    'income',   10),
  ('Income',    'Other income',           'income',   20),
  ('Home',      'Mortgage',               'expense',  10),
  ('Home',      'Rent and utilities',     'expense',  20),
  ('Home',      'Home improvement',       'expense',  30),
  ('Home',      'Insurance',              'expense',  40),
  ('Everyday',  'Groceries and food',     'expense',  10),
  ('Everyday',  'Merchandise',            'expense',  20),
  ('Everyday',  'Personal care',          'expense',  30),
  ('Everyday',  'Kids',                   'expense',  40),
  ('Transport', 'Transport',              'expense',  10),
  ('Transport', 'Travel',                 'expense',  20),
  ('Health',    'Medical',                'expense',  10),
  ('Lifestyle', 'Entertainment',          'expense',  10),
  ('Lifestyle', 'Services',               'expense',  20),
  ('Lifestyle', 'Community and government', 'expense', 30),
  ('Money',     'Bank fees',              'expense',  10),
  ('Money',     'Loan payments',          'expense',  20),
  ('Transfers', 'Internal transfer',      'transfer', 10)
) as c(group_name, name, kind, sort_order)
join categories g on g.name = c.group_name and g.parent_id is null;

-- Every top level provider category Redbark serves, mapped onto the above.
insert into provider_category_map (provider_category, category_id)
select m.provider_category, c.id
from (values
  ('INCOME',                    'Other income'),
  ('RENT_AND_UTILITIES',        'Rent and utilities'),
  ('HOME_IMPROVEMENT',          'Home improvement'),
  ('FOOD_AND_DRINK',            'Groceries and food'),
  ('MERCHANDISE',               'Merchandise'),
  ('PERSONAL_CARE',             'Personal care'),
  ('TRANSPORTATION',            'Transport'),
  ('TRAVEL',                    'Travel'),
  ('MEDICAL',                   'Medical'),
  ('ENTERTAINMENT',             'Entertainment'),
  ('SERVICES',                  'Services'),
  ('GOVERNMENT_AND_NON_PROFIT', 'Community and government'),
  ('BANK_FEES',                 'Bank fees'),
  ('LOAN_PAYMENTS',             'Loan payments'),
  ('TRANSFER_IN',               'Internal transfer'),
  ('TRANSFER_OUT',              'Internal transfer')
) as m(provider_category, category_name)
join categories c on c.name = m.category_name and c.parent_id is not null;

insert into schema_migrations (filename) values ('004_seed_taxonomy.sql') on conflict do nothing;

-- ============================================================
-- 005_buckets.sql
-- ============================================================
-- Stage 3: zero based buckets, allocated each pay period.

-- One row, holding how often money arrives and a date we know a pay landed.
-- Everything else is derived from those two facts.
create table pay_cycle (
  id           boolean primary key default true check (id),
  cadence      text not null default 'fortnightly'
               check (cadence in ('weekly', 'fortnightly', 'monthly')),
  anchor_date  date not null,
  updated_at   timestamptz not null default now()
);

-- Generated from the cycle, so a period is a stable thing to hang allocations
-- and reports off.
create table pay_periods (
  id         uuid primary key default gen_random_uuid(),
  starts_on  date not null unique,
  ends_on    date not null,
  created_at timestamptz not null default now(),
  constraint pay_periods_ordered check (ends_on >= starts_on)
);

create index pay_periods_range_idx on pay_periods (starts_on, ends_on);

-- A bucket is a job for money: groceries, fuel, the power bill.
create table buckets (
  id          uuid primary key default gen_random_uuid(),
  name        text not null unique,
  -- What it is for, shown on the buckets page.
  notes       text,
  -- The usual amount to put in each period. Allocations default to this.
  target      numeric(12,2) not null default 0,
  -- Whether what is left over at the end of a period rolls into the next one.
  -- A bill you save up for wants this, a weekly spending allowance does not.
  carry_over  boolean not null default true,
  sort_order  integer not null default 100,
  archived    boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Which categories count as spending from a bucket. A bucket can cover several,
-- for example one Everyday bucket over groceries and merchandise.
create table bucket_categories (
  bucket_id   uuid not null references buckets (id) on delete cascade,
  category_id uuid not null references categories (id) on delete cascade,
  primary key (bucket_id, category_id),
  -- A category belongs to at most one bucket, otherwise spending is counted
  -- twice and the totals stop adding up.
  constraint bucket_categories_category_once unique (category_id)
);

-- What was actually put into a bucket for a period.
create table bucket_allocations (
  id            uuid primary key default gen_random_uuid(),
  bucket_id     uuid not null references buckets (id) on delete cascade,
  pay_period_id uuid not null references pay_periods (id) on delete cascade,
  allocated     numeric(12,2) not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (bucket_id, pay_period_id)
);

create index bucket_allocations_period_idx on bucket_allocations (pay_period_id);

insert into schema_migrations (filename) values ('005_buckets.sql') on conflict do nothing;

-- ============================================================
-- 006_budget_flows.sql
-- ============================================================
-- One definition of what counts as budget activity, so every stage agrees.
--
-- A transfer between two accounts we own is not spending: the money is still
-- ours. There is one exception. Money leaving a spendable account for a loan or
-- a mortgage really does leave our cash, and has to be budgeted for, so it
-- counts. Only the side that leaves the liquid account counts, otherwise the
-- same event would be counted twice.
create view budget_flows as
select
  t.id,
  t.account_id,
  t.txn_date,
  t.posted_date,
  t.amount,
  t.status,
  t.description,
  t.display_description,
  t.category_id,
  t.is_transfer,
  t.transfer_pair_id,
  a.is_liquid                 as from_liquid,
  pa.is_liquid                as to_liquid,
  (
    not t.is_transfer
    or (coalesce(a.is_liquid, false) and not coalesce(pa.is_liquid, true))
  )                           as counts
from transactions t
join accounts a on a.id = t.account_id
left join transactions p on p.id = t.transfer_pair_id
left join accounts pa on pa.id = p.account_id;

insert into schema_migrations (filename) values ('006_budget_flows.sql') on conflict do nothing;

-- ============================================================
-- 007_expected_income.sql
-- ============================================================
-- A job change makes historical income a poor guide to future income, so the
-- forecast needs to be told what to expect rather than inferring it. Null means
-- fall back to what recent periods actually did.
alter table pay_cycle
  add column expected_income numeric(12,2);

insert into schema_migrations (filename) values ('007_expected_income.sql') on conflict do nothing;

-- ============================================================
-- 008_commitments.sql
-- ============================================================
-- Stage 4: recurring commitments, detected from history, used by the forecast.

create table commitments (
  id             uuid primary key default gen_random_uuid(),
  -- A stable key derived from the description, so re-running detection updates
  -- the same row rather than making a new one.
  match_key      text not null unique,
  label          text not null,
  category_id    uuid references categories (id) on delete set null,
  -- Negative, like every other outflow in this app.
  typical_amount numeric(12,2) not null,
  cadence_days   integer not null,
  occurrences    integer not null default 0,
  -- How regular the gaps are, 0 to 1. Detection only keeps the reliable ones.
  regularity     numeric(4,3) not null default 0,
  last_seen      date,
  next_due       date,
  -- Set by hand in the UI: a commitment we know about that history has not
  -- shown yet, or one we want the forecast to ignore.
  source         text not null default 'detected' check (source in ('detected', 'manual')),
  active         boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index commitments_next_due_idx on commitments (next_due) where active;

alter table sync_runs
  add column commitments_found integer not null default 0;

insert into schema_migrations (filename) values ('008_commitments.sql') on conflict do nothing;

-- ============================================================
-- 009_alerts.sql
-- ============================================================
-- Stage 5: email alerts.

-- One row of settings. Alerts are off until an address is set, so nothing is
-- ever sent by surprise.
create table alert_settings (
  id                        boolean primary key default true check (id),
  enabled                   boolean not null default false,
  email_to                  text,
  runway_days_threshold     integer not null default 21,
  large_transaction_amount  numeric(12,2) not null default 500.00,
  notify_bucket_overspend   boolean not null default true,
  notify_sync_failure       boolean not null default true,
  notify_unreviewed         boolean not null default true,
  updated_at                timestamptz not null default now()
);

insert into alert_settings (id) values (true);

-- Every alert considered, whether or not it was sent. The dedupe key is what
-- stops the same warning arriving twice a day: it only changes when the
-- situation meaningfully changes.
create table alert_log (
  id          uuid primary key default gen_random_uuid(),
  kind        text not null,
  dedupe_key  text not null,
  subject     text not null,
  body        text not null,
  status      text not null default 'pending'
              check (status in ('pending', 'sent', 'failed', 'skipped', 'suppressed')),
  error       text,
  created_at  timestamptz not null default now(),
  sent_at     timestamptz
);

create index alert_log_dedupe_idx on alert_log (kind, dedupe_key, created_at desc);
create index alert_log_created_idx on alert_log (created_at desc);

alter table sync_runs
  add column alerts_sent integer not null default 0;

insert into schema_migrations (filename) values ('009_alerts.sql') on conflict do nothing;

-- ============================================================
-- 010_analyst_and_manual_accounts.sql
-- ============================================================
-- Periodic analysis by Claude, and manual accounts for debts open banking
-- cannot see.

-- A credit card or personal loan we hold elsewhere is still part of the
-- picture, so it gets an account with no Redbark id and a balance entered by
-- hand. The roles list grows to name them.
alter table accounts drop constraint if exists accounts_role_check;
alter table accounts
  add constraint accounts_role_check check (role in (
    'joint_everyday', 'personal_everyday', 'personal_savings',
    'mortgage', 'credit_card', 'personal_loan', 'other'
  ));

-- Where a manually entered balance came from, so it is obvious in the UI that
-- nobody is syncing it.
alter table accounts
  add column notes text,
  add column balance_updated_by text;

create table analyses (
  id            uuid primary key default gen_random_uuid(),
  kind          text not null default 'periodic'
                check (kind in ('periodic', 'on_demand', 'question', 'expense_plan')),
  -- What was asked, when someone asked something specific.
  question      text,
  -- Exactly what was sent, kept so an answer can always be checked against the
  -- figures it was given.
  snapshot      jsonb not null,
  result        jsonb not null,
  model         text,
  input_tokens  integer,
  output_tokens integer,
  created_at    timestamptz not null default now()
);

create index analyses_created_idx on analyses (created_at desc);
create index analyses_kind_idx on analyses (kind, created_at desc);

create table analyst_settings (
  id           boolean primary key default true check (id),
  -- Off until someone turns it on. Analysis sends financial figures to the
  -- Claude API, so it is never on by surprise.
  enabled      boolean not null default false,
  cadence_days integer not null default 7,
  effort       text not null default 'high' check (effort in ('low', 'medium', 'high', 'xhigh', 'max')),
  last_run_at  timestamptz,
  updated_at   timestamptz not null default now()
);

insert into analyst_settings (id) values (true);

alter table sync_runs
  add column analysis_run boolean not null default false;

insert into schema_migrations (filename) values ('010_analyst_and_manual_accounts.sql') on conflict do nothing;

-- ============================================================
-- 011_assets_and_expected_income.sql
-- ============================================================
-- Levers the forecast could not see: things we could sell, and income we expect
-- but that has not started yet.

-- A motorbike or a PC is not cash, but it is a lever, so the planner should
-- know it exists without it ever counting as spendable.
create table assets (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  estimated_value numeric(12,2) not null check (estimated_value >= 0),
  notes           text,
  -- Would we actually sell it. Something we own but would not part with still
  -- belongs on the list, marked so.
  sellable        boolean not null default true,
  sold_on         date,
  sort_order      integer not null default 100,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- Income that is coming but is not in the transaction history yet: a job
-- starting, a side income beginning. The forecast counts it from its start
-- date, so a runway is not pessimistic about money we are confident of.
create table expected_income (
  id           uuid primary key default gen_random_uuid(),
  label        text not null,
  amount       numeric(12,2) not null check (amount > 0),
  cadence_days integer not null check (cadence_days > 0),
  starts_on    date,
  ends_on      date,
  -- How sure we are. The planner treats these differently: a confirmed job is
  -- not the same as one we hope for.
  confidence   text not null default 'likely'
               check (confidence in ('confirmed', 'likely', 'possible')),
  notes        text,
  active       boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index expected_income_active_idx on expected_income (active, starts_on);

insert into schema_migrations (filename) values ('011_assets_and_expected_income.sql') on conflict do nothing;

-- ============================================================
-- 012_afford_kind.sql
-- ============================================================
-- The affordability planner is its own kind of analysis.
alter table analyses drop constraint if exists analyses_kind_check;
alter table analyses
  add constraint analyses_kind_check check (kind in (
    'periodic', 'on_demand', 'question', 'expense_plan', 'afford'
  ));

insert into schema_migrations (filename) values ('012_afford_kind.sql') on conflict do nothing;

-- ============================================================
-- 013_budget_flows_liquid_only.sql
-- ============================================================
-- Fix: only money moving out of a spendable account is spending.
--
-- The previous rule counted any non transfer row, which swept in everything
-- charged to the mortgage itself: interest, package fees, rate adjustments.
-- Over a year that was about 35,700 dollars of "spending" that never left the
-- household's cash. It inflated the everyday spend rate and made the runway
-- look far shorter than it is.
--
-- Interest on a loan is real, and it does make the household poorer, but it is
-- a change in what is owed rather than cash going out of the door. The forecast
-- is about cash, so it belongs to the debt, not to the budget.
create or replace view budget_flows as
select
  t.id,
  t.account_id,
  t.txn_date,
  t.posted_date,
  t.amount,
  t.status,
  t.description,
  t.display_description,
  t.category_id,
  t.is_transfer,
  t.transfer_pair_id,
  a.is_liquid                 as from_liquid,
  pa.is_liquid                as to_liquid,
  (
    -- It has to leave a spendable account at all,
    a.is_liquid
    and (
      -- and either not be a transfer between accounts we own,
      not t.is_transfer
      -- or be one that leaves for a loan, which really is cash gone.
      or not coalesce(pa.is_liquid, true)
    )
  )                           as counts
from transactions t
join accounts a on a.id = t.account_id
left join transactions p on p.id = t.transfer_pair_id
left join accounts pa on pa.id = p.account_id;

insert into schema_migrations (filename) values ('013_budget_flows_liquid_only.sql') on conflict do nothing;

-- ============================================================
-- 014_transport_relabel.sql
-- ============================================================
-- "Transport" read as public transport. It was almost entirely fuel. Relabel
-- so the numbers say what they are, and give public transport its own line.
-- Buckets and the provider map follow by id, so nothing else moves.

update categories set name = 'Getting around', updated_at = now()
 where name = 'Transport' and parent_id is null;

update categories set name = 'Fuel and car', updated_at = now()
 where name = 'Transport' and parent_id is not null;

update categories set name = 'Travel and holidays', updated_at = now()
 where name = 'Travel' and parent_id is not null;

insert into categories (parent_id, name, kind, sort_order)
select g.id, 'Public transport', 'expense', 15
  from categories g
 where g.name = 'Getting around' and g.parent_id is null
on conflict (parent_id, name) do nothing;

-- The one rule worth shipping: the Perth transport card is public transport,
-- not fuel, whatever the bank's category says. Delete it if it is unwanted.
insert into rules (position, name, match_field, match_type, match_value, category_id)
select 5, 'SmartRider is public transport', 'any', 'contains', 'SMARTRIDER', c.id
  from categories c
 where c.name = 'Public transport' and c.parent_id is not null
   and not exists (select 1 from rules where name = 'SmartRider is public transport');

insert into schema_migrations (filename) values ('014_transport_relabel.sql') on conflict do nothing;

-- ============================================================
-- 015_merchants.sql
-- ============================================================
-- Making a bank statement legible.
--
-- A description is full of processor prefixes, store numbers and truncation.
-- merchant_key reduces it to something stable, and merchants holds what we call
-- that place and what it actually is. The key is computed in JavaScript and
-- stored, never recomputed in SQL: one definition, for the same reason
-- matchKeyFor has one.
create table merchants (
  match_key    text primary key,
  -- What to show. Two keys that are really the same place, "The Little Bakery"
  -- and a truncated "The Little Baker", are merged by sharing a display name,
  -- which needs no alias table.
  display_name text not null,
  -- Plain English: what this place is and why money goes there. Filled in by
  -- hand or worked out by Claude.
  what_it_is   text,
  -- Where spending here usually belongs.
  category_id  uuid references categories (id) on delete set null,
  source       text not null default 'auto' check (source in ('auto', 'manual', 'claude')),
  -- Things we consider essential are marked, so the trimming view can put them
  -- aside rather than suggesting the household stop paying for power.
  essential    boolean,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index merchants_display_idx on merchants (display_name);

alter table transactions add column merchant_key text;

create index transactions_merchant_idx on transactions (merchant_key);

insert into schema_migrations (filename) values ('015_merchants.sql') on conflict do nothing;

-- ============================================================
-- 016_merchants_analysis_kind.sql
-- ============================================================
-- Identifying merchants is its own kind of analysis.
alter table analyses drop constraint if exists analyses_kind_check;
alter table analyses
  add constraint analyses_kind_check check (kind in (
    'periodic', 'on_demand', 'question', 'expense_plan', 'afford', 'merchants'
  ));

insert into schema_migrations (filename) values ('016_merchants_analysis_kind.sql') on conflict do nothing;

-- ============================================================
-- 017_budget_flows_merchant_key.sql
-- ============================================================
-- budget_flows was created before merchant_key existed, and a view does not
-- pick up columns added to its table afterwards. Spending by merchant is a
-- question about flows, so the key belongs on the view rather than every caller
-- joining back to transactions for it.
--
-- The new columns go on the end. create or replace can append to a view but
-- cannot reorder or rename what is already there, so inserting them next to the
-- other transaction fields fails with "cannot change name of view column".
create or replace view budget_flows as
select
  t.id,
  t.account_id,
  t.txn_date,
  t.posted_date,
  t.amount,
  t.status,
  t.description,
  t.display_description,
  t.category_id,
  t.is_transfer,
  t.transfer_pair_id,
  a.is_liquid                 as from_liquid,
  pa.is_liquid                as to_liquid,
  (
    a.is_liquid
    and (not t.is_transfer or not coalesce(pa.is_liquid, true))
  )                           as counts,
  t.merchant_name,
  t.merchant_key
from transactions t
join accounts a on a.id = t.account_id
left join transactions p on p.id = t.transfer_pair_id
left join accounts pa on pa.id = p.account_id;

insert into schema_migrations (filename) values ('017_budget_flows_merchant_key.sql') on conflict do nothing;

-- ============================================================
-- 018_prediction_accuracy.sql
-- ============================================================
-- Prediction accuracy: three things the forecast was getting wrong.
--
-- 1. One off spending was setting the rate.
--    The 2025 renovation put about 55,000 dollars through the account over a
--    few months. Hiding it behind a short window was a blunt fix: it also threw
--    away the recent history that makes the rate stable, and it only worked
--    until the next large purchase. Backtesting the estimator against the next
--    60 days of real spending, marking one offs and keeping a longer window
--    beat a short window by about 19 percent. So a transaction can now be
--    marked as a one off. It stays in the history and in every total, because
--    it really happened, and it is excluded only where a rate is worked out.
--
-- 2. Unpaired internal transfers were counted as spending.
--    ING writes the destination account number into the description of a
--    transfer between two of our own accounts. When the other side had not been
--    synced yet, or the destination is not connected, the pair never formed and
--    budget_flows counted the money as gone. It was not gone, it was in the
--    next account along. That was about 710 dollars a month of phantom
--    spending, which shortened the runway for no reason.
--
--    The destination is resolved from the account number in the description
--    instead, so the pair does not have to exist. The liquid rule is unchanged:
--    money moving to another spendable account is not spending, money moving to
--    a loan or a card is.
--
-- 3. There was nowhere to record that a bill is annual.
--    Commitment detection ignores anything with a cadence over 200 days, so
--    rates, rego, insurance and health cover never reached the forecast. They
--    are real and predictable, so they get a flag that lets them be confirmed
--    by hand rather than guessed at from two occurrences.

alter table transactions
  add column if not exists one_off boolean not null default false,
  add column if not exists internal_to_account_id uuid references accounts(id);

comment on column transactions.one_off is
  'Excluded from spend rates and provisions, kept in every total. Set by a person.';
comment on column transactions.internal_to_account_id is
  'Destination account, resolved from the account number in the description when no counterpart row exists.';

create index if not exists transactions_one_off_idx on transactions (one_off) where one_off;

-- Long cadence commitments, confirmed rather than detected. The detector will
-- not create these, so they are never stood down for having gone quiet.
alter table commitments
  add column if not exists annual boolean not null default false;

comment on column commitments.annual is
  'A bill that repeats too rarely for detection to believe in. Entered or confirmed by a person.';

-- budget_flows gains one_off so callers can exclude it from a rate, and starts
-- respecting a resolved internal destination. New columns go on the end:
-- create or replace can append but cannot reorder.
create or replace view budget_flows as
select
  t.id,
  t.account_id,
  t.txn_date,
  t.posted_date,
  t.amount,
  t.status,
  t.description,
  t.display_description,
  t.category_id,
  t.is_transfer,
  t.transfer_pair_id,
  a.is_liquid                 as from_liquid,
  pa.is_liquid                as to_liquid,
  (
    -- It has to leave a spendable account at all,
    a.is_liquid
    -- and not be a transfer between accounts we own, whether that was proved
    -- by a matched counterpart or read out of the description,
    and (not t.is_transfer or not coalesce(pa.is_liquid, true))
    and (t.internal_to_account_id is null or not coalesce(ia.is_liquid, false))
  )                           as counts,
  t.merchant_name,
  t.merchant_key,
  t.one_off,
  t.internal_to_account_id
from transactions t
join accounts a on a.id = t.account_id
left join transactions p on p.id = t.transfer_pair_id
left join accounts pa on pa.id = p.account_id
left join accounts ia on ia.id = t.internal_to_account_id;

insert into schema_migrations (filename) values ('018_prediction_accuracy.sql') on conflict do nothing;

-- ============================================================
-- 019_intentions.sql
-- ============================================================
-- Decisions, with a date and a way to check them.
--
-- "We should spend less on takeaway" changes nothing. The research on this is
-- unusually clear: a goal paired with a specific plan for when and where it
-- applies is followed through far more often than the same goal on its own.
-- So a decision made here is stored as a thing, a trigger, and a date, not as
-- a good feeling at the end of a session with the numbers.
--
-- The important column is merchant_key. A tick box records what someone
-- intended. Checking whether the charges actually stopped records what
-- happened. Those are different, and only the second one is worth reporting,
-- so this table is verified against the transactions rather than trusted.
create table if not exists intentions (
  id               uuid primary key default gen_random_uuid(),
  what             text not null,
  -- The "when" half of an implementation intention: the situation that should
  -- trigger the action. "When the renewal email arrives", "before the weekly
  -- shop". Optional, because some decisions are a single act.
  trigger_text     text,
  -- What to watch to see whether it happened. Null when nothing observable
  -- would change, in which case this stays a self reported decision and is
  -- labelled as one.
  merchant_key     text,
  -- What we expect it to be worth per month, for ranking and for honesty about
  -- whether the effort was worth it.
  target_monthly   numeric(12,2),
  starts_on        date not null default current_date,
  review_on        date,
  status           text not null default 'open' check (status in ('open', 'kept', 'slipped', 'dropped')),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists intentions_status_idx on intentions (status, review_on);

-- The household's own goals, so a trade off can be expressed as "this delays
-- the bike by five weeks" rather than as a number of dollars. A dollar is
-- abstract. A date the thing arrives is not.
create table if not exists goals (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  target       numeric(12,2) not null,
  saved        numeric(12,2) not null default 0,
  wanted_by    date,
  active       boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

insert into schema_migrations (filename) values ('019_intentions.sql') on conflict do nothing;

-- ============================================================
-- 020_settings.sql
-- ============================================================
-- A small key and value store for household choices that do not deserve a
-- table of their own.
--
-- The first one is the change point: the date the household last changed shape,
-- which is what "did the cut stick" measures from. It can be guessed at from
-- the data, and the guess is usually right, but only a person knows why the
-- spending changed. The guess is a suggestion and the stored value wins, for
-- the same reason the pay cycle is configured rather than inferred.
create table if not exists settings (
  key         text primary key,
  value       text,
  updated_at  timestamptz not null default now()
);

insert into schema_migrations (filename) values ('020_settings.sql') on conflict do nothing;

-- ============================================================
-- 021_debt_vs_living.sql
-- ============================================================
-- Paying down what you owe is not the same as spending it.
--
-- Cash leaving a spendable account for a loan or a card really is cash gone, so
-- it belongs in the runway exactly as it is. But it is not consumption: it buys
-- down a liability rather than buying anything. Lumping the two together makes
-- "going out 17,900 a month" true and useless, because a third of that figure
-- is not a choice anyone makes each month and none of it is trimmable in the
-- way the rest is.
--
-- On this household the split is about 12,500 a month of living and 5,400 a
-- month of debt servicing.
--
-- Two ways a payment is known to be servicing our own debt:
--
--   1. It is a transfer whose far side is one of our non liquid accounts. That
--      already worked, through a matched counterpart or through the account
--      number in the description.
--
--   2. It is paid to a merchant that exists to service one of those accounts:
--      the card issuer, the finance company. Those accounts are entered by hand
--      because open banking cannot reach them, so there is no counterpart row to
--      pair with and the only link is the payee. That link is what
--      merchants.pays_account_id records.
--
-- The savings shuffle is neither of these and stays excluded from everything, as
-- it already was: money moved between two spendable accounts we own has not
-- gone anywhere.
alter table merchants
  add column if not exists pays_account_id uuid references accounts(id);

comment on column merchants.pays_account_id is
  'This payee services that account. Set through the UI, never from a literal in source.';

-- to_own_debt goes on the end: create or replace can append to a view but cannot
-- reorder or rename what is already there.
create or replace view budget_flows as
select
  t.id,
  t.account_id,
  t.txn_date,
  t.posted_date,
  t.amount,
  t.status,
  t.description,
  t.display_description,
  t.category_id,
  t.is_transfer,
  t.transfer_pair_id,
  a.is_liquid                 as from_liquid,
  pa.is_liquid                as to_liquid,
  (
    a.is_liquid
    and (not t.is_transfer or not coalesce(pa.is_liquid, true))
    and (t.internal_to_account_id is null or not coalesce(ia.is_liquid, false))
  )                           as counts,
  t.merchant_name,
  t.merchant_key,
  t.one_off,
  t.internal_to_account_id,
  (
    -- Money out, landing on one of our own non liquid accounts.
    t.amount < 0
    and (
      (pa.id is not null and not pa.is_liquid)
      or (ia.id is not null and not ia.is_liquid)
      or (ma.id is not null and not ma.is_liquid)
    )
  )                           as to_own_debt
from transactions t
join accounts a on a.id = t.account_id
left join transactions p on p.id = t.transfer_pair_id
left join accounts pa on pa.id = p.account_id
left join accounts ia on ia.id = t.internal_to_account_id
left join merchants mm on mm.match_key = t.merchant_key
left join accounts ma on ma.id = mm.pays_account_id;

insert into schema_migrations (filename) values ('021_debt_vs_living.sql') on conflict do nothing;

-- ============================================================
-- 022_account_identity.sql
-- ============================================================
-- An account is identified by its number at its bank, not by a Redbark id.
--
-- Relinking a connection, which happens whenever consent is renewed and CDR
-- consent expires every twelve months, issues brand new account ids for every
-- account behind it. Adding the personal loan to the ING connection did exactly
-- that: all four ING accounts came back with ids we had never seen.
--
-- upsertAccounts only knew how to conflict on redbark_account_id, so that would
-- have inserted four new accounts and left the originals orphaned, still
-- holding every transaction, every balance, and the is_liquid and role settings
-- that the whole forecast depends on. Spendable cash would have been read off
-- the new empty rows. Nothing would have errored.
--
-- The stable identity is the institution plus the masked number, so that is
-- what gets the unique index. A manually created account can then be adopted by
-- the connection that later starts serving it, keeping its balance and its role,
-- which is what happened to the personal loan here.
--
-- Partial, because accounts entered by hand for debts open banking cannot reach
-- have no masked number at all and several of them would otherwise collide on
-- null.
create unique index if not exists accounts_bank_number_idx
  on accounts (bank, masked_number)
  where masked_number is not null;

insert into schema_migrations (filename) values ('022_account_identity.sql') on conflict do nothing;

-- ============================================================
-- 023_reversals.sql
-- ============================================================
-- A charge that was refunded is not spending, and its refund is not income.
--
-- Real statements carry reversals: a contractor charged 1,419 dollars and
-- refunded it the same day, a subscription double billed and gave one back, a
-- card investigation reversed a disputed charge. Both halves were being counted.
-- The charge went into spending because it is a negative amount leaving a
-- spendable account, and the refund came back as "Other income" because the
-- provider categorises an unexplained credit that way. So a payment that never
-- really happened inflated spending AND income by the same amount, and the
-- household's biggest single "merchandise" merchant was a reversal.
--
-- This is the transfer problem again, in a different costume, so it gets the
-- same answer: pair the two sides and let budget_flows exclude the pair. That
-- needs no change at the twenty four places that filter on amount, because they
-- all go through counts already.
--
-- Pairing is deliberately strict. Same merchant, same amount to the cent,
-- refund on or after the charge and within thirty days, and each row used once.
-- A positive amount that finds no charge to cancel is left exactly as it was: it
-- might be a rebate, a cashback, or money someone sent us, and guessing is worse
-- than leaving it alone.
alter table transactions
  add column if not exists reversal_of_id uuid references transactions(id);

comment on column transactions.reversal_of_id is
  'This credit cancels that charge. Both sides stop counting as spending or income.';

create index if not exists transactions_reversal_of_idx on transactions (reversal_of_id)
  where reversal_of_id is not null;

-- counts gains one more condition: neither side of a reversal counts. The new
-- column goes on the end, since create or replace can append but not reorder.
create or replace view budget_flows as
select
  t.id,
  t.account_id,
  t.txn_date,
  t.posted_date,
  t.amount,
  t.status,
  t.description,
  t.display_description,
  t.category_id,
  t.is_transfer,
  t.transfer_pair_id,
  a.is_liquid                 as from_liquid,
  pa.is_liquid                as to_liquid,
  (
    a.is_liquid
    and (not t.is_transfer or not coalesce(pa.is_liquid, true))
    and (t.internal_to_account_id is null or not coalesce(ia.is_liquid, false))
    -- Not the credit that cancels a charge,
    and t.reversal_of_id is null
    -- and not the charge that a credit cancelled.
    and not exists (select 1 from transactions r where r.reversal_of_id = t.id)
  )                           as counts,
  t.merchant_name,
  t.merchant_key,
  t.one_off,
  t.internal_to_account_id,
  (
    t.amount < 0
    and (
      (pa.id is not null and not pa.is_liquid)
      or (ia.id is not null and not ia.is_liquid)
      or (ma.id is not null and not ma.is_liquid)
    )
  )                           as to_own_debt,
  t.reversal_of_id
from transactions t
join accounts a on a.id = t.account_id
left join transactions p on p.id = t.transfer_pair_id
left join accounts pa on pa.id = p.account_id
left join accounts ia on ia.id = t.internal_to_account_id
left join merchants mm on mm.match_key = t.merchant_key
left join accounts ma on ma.id = mm.pays_account_id;

insert into schema_migrations (filename) values ('023_reversals.sql') on conflict do nothing;

-- ============================================================
-- 024_merchant_ended.sql
-- ============================================================
-- A cost that has been cancelled should stop being forecast.
--
-- The household changed insurers. Six Youi policies worth about 614 a month are
-- still in the window, so the spend rate still expects them, and the forecast
-- will keep expecting them for as long as the window remembers. Nothing is
-- wrong with the history: those payments really happened. What is wrong is
-- treating them as a guide to next month, which is the same distinction
-- transactions.one_off already makes, but about a merchant rather than a
-- purchase, and about everything it charges from here on rather than one row.
--
-- The same thing is needed every time a subscription is cancelled, a gym is
-- quit, or a service is switched, and a decision on the Today page that is
-- verified as held is exactly this. Waiting for commitment detection to stand
-- it down takes two full cycles, which is two months of a forecast that is
-- knowably wrong.
alter table merchants
  add column if not exists ended_on date;

comment on column merchants.ended_on is
  'No longer expected from this date. Kept in history and in every total, left out of any rate.';

-- budget_flows gains one flag for it. New column on the end: create or replace
-- can append but cannot reorder.
create or replace view budget_flows as
select
  t.id,
  t.account_id,
  t.txn_date,
  t.posted_date,
  t.amount,
  t.status,
  t.description,
  t.display_description,
  t.category_id,
  t.is_transfer,
  t.transfer_pair_id,
  a.is_liquid                 as from_liquid,
  pa.is_liquid                as to_liquid,
  (
    a.is_liquid
    and (not t.is_transfer or not coalesce(pa.is_liquid, true))
    and (t.internal_to_account_id is null or not coalesce(ia.is_liquid, false))
    and t.reversal_of_id is null
    and not exists (select 1 from transactions r where r.reversal_of_id = t.id)
  )                           as counts,
  t.merchant_name,
  t.merchant_key,
  t.one_off,
  t.internal_to_account_id,
  (
    t.amount < 0
    and (
      (pa.id is not null and not pa.is_liquid)
      or (ia.id is not null and not ia.is_liquid)
      or (ma.id is not null and not ma.is_liquid)
    )
  )                           as to_own_debt,
  t.reversal_of_id,
  -- True once the merchant has been marked as finished with. Kept out of rates,
  -- never out of history.
  (mm.ended_on is not null)   as no_longer_expected
from transactions t
join accounts a on a.id = t.account_id
left join transactions p on p.id = t.transfer_pair_id
left join accounts pa on pa.id = p.account_id
left join accounts ia on ia.id = t.internal_to_account_id
left join merchants mm on mm.match_key = t.merchant_key
left join accounts ma on ma.id = mm.pays_account_id;

insert into schema_migrations (filename) values ('024_merchant_ended.sql') on conflict do nothing;

commit;
