#!/bin/bash
# Rolls every migration into one file that can be pasted into a psql console,
# for setting up a database somewhere Node is not available. The migration
# runner is still the normal path: this is for first time setup from a browser.
#
#   npm run bootstrap-sql
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=scripts/bootstrap-schema.sql

{
  echo "-- FamilyBudget: every migration, in order, as one file."
  echo "-- Generated by scripts/build-bootstrap-sql.sh. Do not edit by hand."
  echo "--"
  echo "-- For setting up a fresh database without Node, for example by pasting"
  echo "-- into the psql console in the Render dashboard. It runs in a single"
  echo "-- transaction, so a failure anywhere leaves the database untouched, and"
  echo "-- it records each file in schema_migrations, so a later 'npm run migrate'"
  echo "-- sees the work as already done and changes nothing."
  echo
  echo "begin;"
  echo
  echo "create table if not exists schema_migrations ("
  echo "  filename    text primary key,"
  echo "  applied_at  timestamptz not null default now()"
  echo ");"
  echo
  for f in migrations/*.sql; do
    name=$(basename "$f")
    echo "-- ============================================================"
    echo "-- $name"
    echo "-- ============================================================"
    cat "$f"
    echo
    echo "insert into schema_migrations (filename) values ('$name') on conflict do nothing;"
    echo
  done
  echo "commit;"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines, $(ls migrations/*.sql | wc -l) migrations)"
